### ISSUE TITLE
Netflix namespace problem

### ISSUE THREAD

**Issue by szczys** [home-assistant-libs/pychromecast#34]
Great work on this package. I'm trying to get "pause" to work with Netflix and understand I need to add my own namespace. Here's my object:

```
class MyController(BaseController):
    def __init__(self):
        super(MediaController, self).__init__("urn:x-cast:mdx-netflix-com")
    def receive_message(self, message, data):
        print("Wow, I received this message: {}".format(data))
        return True
    def do_pause(self):
        self.send_message("PAUSE", inc_session_id=True)
```

Which I instantiate and register. But when I try to use it I get an error:

```
>>> cast.status
CastStatus(is_active_input=True, is_stand_by=False, volume_level=1.0, volume_muted=False, app_id=u'REMOVED', display_name=u'Netflix', namespaces=[u'urn:x-cast:mdx-netflix-com:service:target:2'], session_id=u'REMOVEDFORTHISPOST', transport_id=u'web-2', status_text='')
>>> netflix = MediaController()
>>> cast.register_handler(netflix)
>>> netflix.do_pause()

Traceback (most recent call last):
  File "<pyshell#84>", line 1, in <module>
    netflix.do_pause()
  File "<pyshell#52>", line 8, in do_pause
    self.send_message("PAUSE", inc_session_id=True)
  File "/usr/local/lib/python2.7/dist-packages/PyChromecast-0.6-py2.7.egg/pychromecast/controllers/__init__.py", line 77, in send_message
    "application.").format(self.namespace))
UnsupportedNamespace: Namespace urn:x-cast:mdx-netflix-com is not supported by runningapplication.
```

Any idea where I'm going wrong?

**Comment by madteckhead** [comment]
@szczys Any luck? Were you able to launch a specific video on netflix? Thanks for any pointers.

**Comment by fadnavis** [comment]
@szczys any progress? I am stuck at the exact same point. Thanks in advance!

**Comment by szczys** [comment]
I abandoned this project shortly after posting here. Sorry.
