### ISSUE TITLE
Chromecast discovery leads to "No buffer space available"

### ISSUE THREAD

**Issue by EtienneM** [home-assistant-libs/pychromecast#478]
I tried this library with the software catt. I first opened an issue in catt repository (https://github.com/skorokithakis/catt/issues/328), but the maintainer told me this is probably an issue in PyChromecast. 

When I use the discovery function I receive a "No buffer space available" error. I have no idea what could lead to this. I tried with PyChromecast 8 and 9. Here is the stack trace with the latest version of catt and PyChromecast:

```
╰─$ pip3 install catt        
Collecting catt
  Using cached catt-0.12.1-py2.py3-none-any.whl (27 kB)
Collecting youtube-dl>=2020.9.20
  Using cached youtube_dl-2021.3.14-py2.py3-none-any.whl (1.9 MB)
Collecting Click<8,>=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting PyChromecast>=9.0.0
  Using cached PyChromecast-9.1.1-py2.py3-none-any.whl (61 kB)
Collecting ifaddr>=0.1.7
  Using cached ifaddr-0.1.7-py2.py3-none-any.whl (10 kB)
Collecting requests>=2.23.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting casttube>=0.2.0
  Using cached casttube-0.2.1-py3-none-any.whl (6.5 kB)
Requirement already satisfied: protobuf>=3.0.0 in /usr/lib/python3/dist-packages (from PyChromecast>=9.0.0->catt) (3.6.1)
Collecting zeroconf>=0.25.1
  Using cached zeroconf-0.28.8-py3-none-any.whl (55 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.23.0->catt) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.23.0->catt) (2019.11.28)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.23.0->catt) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.23.0->catt) (2.8)
Installing collected packages: youtube-dl, Click, requests, casttube, ifaddr, zeroconf, PyChromecast, catt
Successfully installed Click-7.1.2 PyChromecast-9.1.1 casttube-0.2.1 catt-0.12.1 ifaddr-0.1.7 requests-2.25.1 youtube-dl-2021.3.14 zeroconf-0.28.8

╰─$ catt scan                                                                                                                                                                                                  2 ↵
Scanning Chromecasts...
Traceback (most recent call last):
  File "/home/titi/.local/bin/catt", line 8, in <module>
    sys.exit(main())
  File "/home/titi/.local/lib/python3.8/site-packages/catt/cli.py", line 644, in main
    return cli(obj=get_config_as_dict())
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/titi/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/titi/.local/lib/python3.8/site-packages/catt/cli.py", line 483, in scan
    devices = get_cast_devices_info()
  File "/home/titi/.local/lib/python3.8/site-packages/catt/discovery.py", line 65, in get_cast_devices_info
    devices = get_cast_devices()
  File "/home/titi/.local/lib/python3.8/site-packages/catt/discovery.py", line 47, in get_cast_devices
    cast_infos, browser = pychromecast.discovery.discover_chromecasts()
  File "/home/titi/.local/lib/python3.8/site-packages/pychromecast/discovery.py", line 506, in discover_chromecasts
    zconf = zeroconf_instance or zeroconf.Zeroconf()
  File "/home/titi/.local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2493, in __init__
    self._listen_socket, self._respond_sockets = create_sockets(
  File "/home/titi/.local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2328, in create_sockets
    respond_socket = add_multicast_member(cast(socket.socket, listen_socket), i, apple_p2p=apple_p2p)
  File "/home/titi/.local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2273, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
``` 

Note that I can use catt on a different computer. This is a fresh install I'm trying here. 

Any idea what could lead to this error? :)

edit: I tried to clone this repository, install the requirements, and execute the code provided in the README:

```
╰─$ python3                                                                                                                                                                                                  127 ↵
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>> import pychromecast
>>> services, browser = pychromecast.discovery.discover_chromecasts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/titi/Videos/pychromecast/pychromecast/discovery.py", line 506, in discover_chromecasts
    zconf = zeroconf_instance or zeroconf.Zeroconf()
  File "/home/titi/.local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2493, in __init__
    self._listen_socket, self._respond_sockets = create_sockets(
  File "/home/titi/.local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2328, in create_sockets
    respond_socket = add_multicast_member(cast(socket.socket, listen_socket), i, apple_p2p=apple_p2p)
  File "/home/titi/.local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2273, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
```

**Comment by balloob** [comment]
This is an issue in your OS.

**Comment by wwwescape** [comment]
I know this is an old and closed issue but I found something that could help.

Please check the blog post [here](https://blog.mphomphego.co.za/blog/2017/06/28/why-am-i-getting-errno105-no-buffer-space-available-when-subscribing-to-multicast-addresses.html#:~:text=The%20%22Errno%20105%22%20in%20this,groups%20at%20the%20same%20time.).

**Comment by fivestones** [comment]
@wwwescape your blog post fixed my problem.
