### ISSUE TITLE
Timeout when waiting for status response from Spotify app

### ISSUE THREAD

**Issue by axolotlgeoff** [home-assistant-libs/pychromecast#528]
Sometimes it seems like my Chromecast device (Nest Home Hub Max) gets into a bad state where it has half started Spotify. When this happens the Home app shows that Spotify is active and using another utility I can see that the device has an active app_id however `cast.app_id` is `None`. When trying to launch the Spotify app the logging shows it's already launched.

Here's an example script that demonstrates the issue:
```
import logging
import os

import pychromecast
import spotify_token as st
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from pychromecast.controllers.spotify import SpotifyController

logging.basicConfig(level=logging.INFO)

device_name = os.environ['CHROMECAST_DEVICE_NAME']
device_ip_address = os.environ['CHROMECAST_DEVICE_IP_ADDRESS']
sp_dc = os.environ['SP_DC']
sp_key = os.environ['SP_KEY']
spotify_uri = os.environ['SPOTIFY_URI']

access_token, expires = st.start_session(sp_dc, sp_key)

scope = "user-library-read user-read-playback-state user-modify-playback-state user-read-currently-playing streaming app-remote-control user-read-playback-position playlist-read-private playlist-read-collaborative"
client = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))

cast = pychromecast.Chromecast(device_ip_address)

logging.info("app_id: %s", cast.app_id)
logging.info(cast.status)

sp = SpotifyController(access_token, expires)
cast.register_handler(sp)
cast.wait()
sp.launch_app()

if not sp.is_launched and not sp.credential_error:
    logging.error('Failed to launch spotify controller due to timeout')
if not sp.is_launched and sp.credential_error:
    logging.error('Failed to launch spotify controller due to credentials error')

devices_available = client.devices()
for device in devices_available['devices']:
    if device['name'] == device_name:
        client.start_playback(device_id=device['id'], context_uri=spotify_uri)
```

The full output:
```
$ python3 example.py 
INFO:pychromecast:Querying device status
INFO:root:app_id: None
INFO:root:None
INFO:pychromecast.controllers:Not launching app CC32E753 - already running
Traceback (most recent call last):
  File "example.py", line 31, in <module>
    sp.launch_app()
  File "/home/pi/.local/lib/python3.7/site-packages/pychromecast/controllers/spotify.py", line 88, in launch_app
    "Timeout when waiting for status response from Spotify app"
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
```

The only way I can get things back into a working state is by opening the Home app and pressing "Stop casting". If I try to do a `cast.quit_app()` I get this:
```
$ python3 example.py 
INFO:pychromecast:Querying device status
INFO:pychromecast:Quiting current app
INFO:pychromecast.controllers:Receiver:Stopping current app 'None'
Traceback (most recent call last):
  File "example.py", line 24, in <module>
    cast.quit_app()
  File "/home/pi/.local/lib/python3.7/site-packages/pychromecast/__init__.py", line 450, in quit_app
    self.socket_client.receiver_controller.stop_app()
  File "/home/pi/.local/lib/python3.7/site-packages/pychromecast/controllers/receiver.py", line 174, in stop_app
    callback_function=callback_function_param,
  File "/home/pi/.local/lib/python3.7/site-packages/pychromecast/controllers/__init__.py", line 91, in send_message
    self.send_message_nocheck(data, inc_session_id, callback_function)
  File "/home/pi/.local/lib/python3.7/site-packages/pychromecast/controllers/__init__.py", line 95, in send_message_nocheck
    self._message_func(self.namespace, data, inc_session_id, callback_function)
  File "/home/pi/.local/lib/python3.7/site-packages/pychromecast/socket_client.py", line 926, in send_platform_message
    callback_function_param,
  File "/home/pi/.local/lib/python3.7/site-packages/pychromecast/socket_client.py", line 858, in send_message
    self._ensure_channel_connected(destination_id)
  File "/home/pi/.local/lib/python3.7/site-packages/pychromecast/socket_client.py", line 975, in _ensure_channel_connected
    no_add_request_id=True,
  File "/home/pi/.local/lib/python3.7/site-packages/pychromecast/socket_client.py", line 914, in send_message
    "Chromecast {}:{} is connecting...".format(self.host, self.port)
pychromecast.error.NotConnected: Chromecast 192.168.1.14:8009 is connecting...
```

Any ideas where to start tracking this one down?

**Comment by emontnemery** [comment]
The spotify app has is maintained by the spotcast project and has been removed from pychromecast. Please open an issue there instead 👍
