### ISSUE TITLE
cast.wait() AssertionError

### ISSUE THREAD

**Issue by busterbeam** [home-assistant-libs/pychromecast#538]
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/pychromecast/socket_client.py", line 513, in run
    self.initialize_connection()
  File "/usr/local/lib/python3.7/dist-packages/pychromecast/socket_client.py", line 297, in initialize_connection
    service, self.zconf
  File "/usr/local/lib/python3.7/dist-packages/pychromecast/dial.py", line 32, in get_host_from_service
    service_info = zconf.get_service_info("_googlecast._tcp.local.", service.data)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/_core.py", line 490, in get_service_info
    if info.request(self, timeout, question_type):
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/_services/info.py", line 434, in request
    assert zc.loop is not None and zc.loop.is_running()
AssertionError
```
chromecast is `waited` on... what is going on here?

**Comment by emontnemery** [comment]
It's not clear from this issue what the problem is.

Please open a new issue where you clearly explain:
- What you tried to do
- What did you expect to happen
- What happened instead
