### ISSUE TITLE
'pychromecast' has no attribute 'get_chromecast'

### ISSUE THREAD

**Issue by PowaBanga** [home-assistant-libs/pychromecast#557]
Hi everyone,
i am on Archlinux, i use pychromecast with rhythmbox-chormecast, and i recieve this error message :
```
Traceback (most recent call last):
  File "/home/powabanga/.local/share/rhythmbox/plugins/chromecast/Chromecast.py", line 33, in do_activate
    self.source.setup()
  File "/home/powabanga/.local/share/rhythmbox/plugins/chromecast/ChromecastSource.py", line 49, in setup
    self.chromecast = pychromecast.get_chromecast(friendly_name=Prefs.chromecastName)
AttributeError: module 'pychromecast' has no attribute 'get_chromecast'
```
does anybody can help me to fix that ?

**Comment by balloob** [comment]
You should report that to https://github.com/KeizerDev/Rhythmbox-Chromecast
