### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'media_controller'　？？

### ISSUE THREAD

**Issue by youtube-dl-fun** [home-assistant-libs/pychromecast#589]
Nice to meet you

【OS】
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

【python】
python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

【pychromecast】
PyChromecast        9.2.0

【Details of the problem】
（１）
>>> import pychromecast
>>> cast = pychromecast.get_chromecasts()
>>> mc = cast.media_controller
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'media_controller'
>>> 

（２）
>>> import time
>>> import pychromecast
>>> chromecasts = pychromecast.get_chromecasts()
>>> [cc.device.friendly_name for cc in chromecasts]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
AttributeError: 'list' object has no attribute 'device'

Why do you get an error?　Please give me some advice

**Comment by youtube-dl-fun** [comment]
catt was also malfunctioning, so when I reinstalled it, the error disappeared.
