### ISSUE TITLE
Cannot initialize 'Chromecast' class 

### ISSUE THREAD

**Issue by TheonlyIcebear** [home-assistant-libs/pychromecast#742]
While looking at this issue: https://github.com/home-assistant-libs/pychromecast/issues/372

I tried using the code here:

```py
import by Chromecast

cast = pychromecast.Chromecast('192.168.0.164')
cast.wait()
print(cast.device)
```

but then I get this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ekila\AppData\Local\Programs\Python\Python310\lib\site-packages\pychromecast\__init__.py", line 269, in __init__
    if not cast_info.cast_type:
AttributeError: 'str' object has no attribute 'cast_type'
```

I'm sure this isn't a problem with how I'm using the module and just a general error, that needs fixing. I am also not able to detect any of my Smart TVs with the module. When I got to cast on YouTube I could see all three of them but when this module I couldn't see any of them. Perhaps it's the fact that I have a Wi-Fi card installed into my PC with no antennas, I'm not sure though

**Comment by Kaelorn** [comment]
I have the same issue

**Comment by Reupireup** [comment]
same here :(
