### ISSUE TITLE
WARNING:pychromecast.controllers:SEEK command requested but no session is active

### ISSUE THREAD

**Issue by elibroftw** [home-assistant-libs/pychromecast#897]
Not really sure why I'm getting `WARNING:pychromecast.controllers:SEEK command requested but no session is active`

```
WARNING:pychromecast.socket_client:[Office speaker(192.168.0.207):8009] Error communicating with socket, resetting connection
WARNING:pychromecast.socket_client:[Office speaker(192.168.0.207):8009] Heartbeat timeout, resetting connection
WARNING:pychromecast.controllers:SEEK command requested but no session is active.
WARNING:pychromecast.controllers:SEEK command requested but no session is active.
```

**Comment by elibroftw** [comment]
Also getting 

`encountered error while seeking: Execution of seek 3.0 timed out after 10.0 s`

**Comment by elibroftw** [comment]
```
Traceback (most recent call last):
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 533, in run
    if self._run_once(timeout=POLL_TIME_BLOCKING) == 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 553, in _run_once
    if not self._check_connection():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 682, in _check_connection
    self.initialize_connection()
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 245, in initialize_connection
    for callback_function in self._request_callbacks.values():
RuntimeError: dictionary changed size during iteration

**Comment by elibroftw** [comment]
```
ERROR:pychromecast.socket_client:[Office speaker(192.168.0.207):8009] Error reading from socket.
WARNING:pychromecast.socket_client:[Office speaker(192.168.0.207):8009] Error communicating with socket, resetting connection
ERROR:pychromecast.socket_client:[Office speaker(192.168.0.207):8009] Unhandled exception in worker thread, attempting reconnect
Traceback (most recent call last):
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 533, in run
    if self._run_once(timeout=POLL_TIME_BLOCKING) == 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 553, in _run_once
    if not self._check_connection():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 682, in _check_connection
    self.initialize_connection()
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 245, in initialize_connection
    for callback_function in self._request_callbacks.values():
RuntimeError: dictionary changed size during iteration
WARNING:pychromecast.socket_client:[Office speaker(192.168.0.207):8009] Error communicating with socket, resetting connection
```

**Comment by elibroftw** [comment]
```py
2024-04-18 15:51:54,011 WARNING (655) _check_connection(): [Office speaker(192.168.0.207):8009] Error communicating with socket, resetting connection
2024-04-18 15:51:54,011 WARNING (655) _check_connection(): [Office speaker(192.168.0.207):8009] Error communicating with socket, resetting connection
2024-04-18 15:51:54,012 ERROR (537) run(): [Office speaker(192.168.0.207):8009] Unhandled exception in worker thread, attempting reconnect
Traceback (most recent call last):
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 533, in run
    if self._run_once(timeout=POLL_TIME_BLOCKING) == 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 553, in _run_once
    if not self._check_connection():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 682, in _check_connection
    self.initialize_connection()
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\socket_client.py", line 306, in initialize_connection
    host, port, service_info = get_host_from_service(
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\pychromecast\dial.py", line 42, in get_host_from_service
    service_info = zconf.get_service_info("_googlecast._tcp.local.", service.name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maste\Documents\GitHub\music-caster\.venv\Lib\site-packages\zeroconf\_core.py", line 276, in get_service_info
    if info.request(self, timeout, question_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\zeroconf\\_services\\info.py", line 780, in zeroconf._services.info.ServiceInfo.request
AssertionError
```

**Comment by elibroftw** [comment]
This is a pychromecast issue and not a zeroconf issue because my last release before using v14 was using zeroconf==0.131.0 already.

**Comment by elibroftw** [comment]
How do you fix this?

`Execution of wait timed out after 5 s.'`

**Comment by elibroftw** [comment]
Even `mc.stop()` results in a RequestFailed...

**Comment by elibroftw** [comment]
Even quit app does this
```py
"pychromecast/__init.py", line 463, in quit_app
File "pychromecast/response_handler.py", line 54, in wait_response
pychromecast.error.RequestTimeout: Execution of quit app timed out after 10.0 s.
```
